name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install || npm ci

      - name: Check for linting issues
        run: npm run lint # Replace with the appropriate lint command, if applicable.

      - name: Run tests
        run: npm test # Ensure your project has a `test` script in `package.json`.

      - name: Build application
        run: npm run build # Ensure your project has a `build` script, if applicable.

      - name: Start application
        run: npm start

